### ISSUE TITLE
hetzner install interrupted cannot find os version that is no longer listed in the library.

### ISSUE THREAD

**Issue by pmdblue** [extremeshok/xshok-proxmox#18]
hetzner install interrupted. looking for debian 9.5 that is no longer in the library

**Comment by extremeshok** [comment]
This will be fixed shortly

**Comment by extremeshok** [comment]
Fixed 979f295

**Comment by pmdblue** [comment]
Hi, the problem is not solved. It now stops trying to write the config file. tried it three times.
